config/routes.rb
Rails.application.routes.draw do
  resources :draft_records
  resources :players
  resources :positions
  resources :teams

  root 'teams#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/position.rb
class Position < ApplicationRecord
    has_many :players, dependent: :destroy
    validates :name, presence: true
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, :set_players, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    def set_players
      @players = Player.where(position_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(position) do |f| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row form-group">
    <div class="col-xs-12 col-md-2 offset-md-3">
      <%= f.label :name %>
    </div>
    <div class="col-xs-12 col-md-4">
        <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  
  <div class="row form-group">
    <div class="col-xs-12 col-md-6 offset-md-3">
      <%= f.submit 'Add Position', :class => 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/positions/edit.html.erb
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
<h1>Editing Position</h1>
    </div>
</div>

<%= render 'form', position: @position %>
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <%= link_to 'Back', positions_path, { :class => 'btn btn-secondary'} %>
    </div>
</div>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-xs-12 col-md-8 offset-md-2">
        <h1>Positions</h1>
        <%= link_to 'New Position', new_position_path, { :class => 'btn btn-primary' }%>
        <div class="table-responsive">
            <table class="table table-striped table-hover table-bordered ">
                <thead class="thead-default">

                    <tr>
                        <th>Name</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @positions.each do |position| %>
                        <tr>
                            <td><%= link_to position.name, position %></td>
                            <td><%= link_to 'Edit', edit_position_path(position) %></td>
                            <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<br>

app/views/positions/new.html.erb
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
<h1>New Position</h1>
    </div>
</div>

<%= render 'form', position: @position %>
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <%= link_to 'Back', positions_path, { :class => 'btn btn-secondary'} %>
    </div>
</div>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <h1><%= @position.name %></h1>

    </div>
    <div class="col-xs-12 col-md-8">
        Total number of <%= @position.name %>s: <%= @players.count %>
        <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
          <thead class="thead-default">
            <tr>
              <th>Name</th>
            </tr>
          </thead>

          <tbody>
            <% @players.each do |player| %>
              <tr>
                <td><%= link_to player.name, player %></td>
              </tr>
            <% end %>
          </tbody>
        </table>


    </div>
    <div class="col-xs-12">
    <%= link_to 'Edit', edit_position_path(@position), { :class => 'btn btn-success'} %>
    <%= link_to 'Back', positions_path, {:class => 'btn btn-secondary' } %>
    </div>
</div>