config/routes.rb
Rails.application.routes.draw do
  resources :draft_records
  resources :players
  resources :positions
  resources :teams

  root 'teams#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/draft_record.rb
class DraftRecord < ApplicationRecord
    belongs_to :player
    belongs_to :team

    validates :player, presence: true
    validates :team, presence: true
end

app/controllers/draft_records_controller.rb
class DraftRecordsController < ApplicationController
  before_action :set_draft_record, only: [:show, :edit, :update, :destroy]

  # GET /draft_records
  # GET /draft_records.json
  def index
    @draft_records = DraftRecord.all
  end

  # GET /draft_records/1
  # GET /draft_records/1.json
  def show
  end

  # GET /draft_records/new
  def new
    @draft_record = DraftRecord.new
  end

  # GET /draft_records/1/edit
  def edit
  end

  # POST /draft_records
  # POST /draft_records.json
  def create
    @draft_record = DraftRecord.new(draft_record_params)

    respond_to do |format|
      if @draft_record.save
        format.html { redirect_to @draft_record, notice: 'Draft record was successfully created.' }
        format.json { render :show, status: :created, location: @draft_record }
      else
        format.html { render :new }
        format.json { render json: @draft_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /draft_records/1
  # PATCH/PUT /draft_records/1.json
  def update
    respond_to do |format|
      if @draft_record.update(draft_record_params)
        format.html { redirect_to @draft_record, notice: 'Draft record was successfully updated.' }
        format.json { render :show, status: :ok, location: @draft_record }
      else
        format.html { render :edit }
        #format.html { render :edit }
        format.json { render json: @draft_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /draft_records/1
  # DELETE /draft_records/1.json
  def destroy
    @draft_record.destroy
    respond_to do |format|
      format.html { redirect_to draft_records_url, notice: 'Draft record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_draft_record
      @draft_record = DraftRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def draft_record_params
      params.require(:draft_record).permit(:player_id, :team_id)
    end
end

app/helpers/draft_records_helper.rb
module DraftRecordsHelper
end

app/views/draft_records/_form.html.erb
<%= form_for(draft_record) do |f| %>
    <% if draft_record.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(draft_record.errors.count, "error") %> prohibited this draft_record from being saved:</h2>

            <ul>
                <% draft_record.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="row form-group">
        <div class="col-xs-12 col-md-2 offset-md-3">
            <%= f.label :player_id %>
        </div>
        <div class="col-xs-12 col-md-4">
            <%= f.collection_select(:player_id, Player.all(), :id, :name, {}, {:class => 'form-control'}) %> 
        </div>
    </div>

    <div class="row form-group">
        <div class="col-xs-12 col-md-2 offset-md-3">
            <%= f.label :team_id %>
        </div>
        <div class="col-xs-12 col-md-4">
            <% if params['team'].present? %>
                <h4><%= Team.find(params['team']).name %></h4>
            <% else %>
                <%= f.collection_select(:team_id, Team.all(), :id, :name, {}, {:class => 'form-control'}) %> 
            <% end %>
        </div>
    </div>

    <div class="row form-group">
        <div class="col-xs-12 col-md-6 offset-md-3">
            <%= f.submit 'Submit', :class => 'btn btn-success' %>
        </div>
    </div>

<% end %>

app/views/draft_records/edit.html.erb
<div class="row">
    <div class="col-xs-12 col-md-8 offset-md-3">
<h1>Editing Draft Record</h1>
    </div>
</div>

<%= render 'form', draft_record: @draft_record %>
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <%= link_to 'Back', draft_records_path, { :class => 'btn btn-secondary'} %>
    </div>
</div>

app/views/draft_records/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-xs-12 col-md-8 offset-md-2">

        <h1>Draft Records</h1>
        <%= link_to 'New Draft Record', new_draft_record_path, { :class => 'btn btn-primary'} %>
        <div class="table-responsive">
            <table class="table table-striped table-hover table-bordered ">
                <thead class="thead-default">

                    <tr>
                        <th>Player</th>
                        <th>Team</th>
                        <th colspan="3"></th>
                    </tr>
                </thead>

                <tbody>
                    <% @draft_records.each do |draft_record| %>
                        <tr>
                            <% player = Player.find(draft_record.player_id) %>
                            <% team = Team.find(draft_record.team_id) %>
                            <td><%= link_to player.name, player %></td>
                            <td><%= link_to team.name, team %></td>
                            <td><%= link_to 'Details', draft_record %></td>
                            <td><%= link_to 'Edit', edit_draft_record_path(draft_record) %></td>
                            <td><%= link_to 'Destroy', draft_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

<br>

app/views/draft_records/new.html.erb
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <h1>New Draft Record</h1>
    </div>
</div>

<%= render 'form', draft_record: @draft_record %>
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <%= link_to 'Back', draft_records_path, { :class => 'btn btn-secondary'} %>
    </div>
</div>

app/views/draft_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @draft_record.player_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @draft_record.team_id %>
</p>

<%= link_to 'Edit', edit_draft_record_path(@draft_record) %> |
<%= link_to 'Back', draft_records_path %>