config/routes.rb
Rails.application.routes.draw do
  resources :draft_records
  resources :players
  resources :positions
  resources :teams

  root 'teams#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :draft_records
    has_many :teams, through: :draft_records

    belongs_to :position
    validates :name, presence: true
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :position_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(player) do |f| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row form-group">
    <div class="col-xs-12 col-md-2 offset-md-3">
      <%= f.label :name %>
    </div>
    <div class="col-xs-12 col-md-4">
        <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  
  <div class="row form-group">
    <div class="col-xs-12 col-md-2 offset-md-3">
      <%= f.label :position_id %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= f.collection_select(:position_id, Position.all(), :id, :name, {}, {:class => 'form-control'}) %> 
    </div>
  </div>

  <div class="row form-group">
    <div class="col-xs-12 col-md-6 offset-md-3">
      <%= f.submit 'Submit', :class => 'btn btn-success' %>
    </div>
  </div>

<% end %>

app/views/players/edit.html.erb
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
<h1>Editing Player</h1>
    </div>
</div>

<%= render 'form', player: @player %>
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <%= link_to 'Back', players_path, { :class => 'btn btn-secondary'} %>
    </div>
</div>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-xs-12 col-md-8 offset-md-2">
        <h1>Players</h1>
        <%= link_to 'New Player', new_player_path, { :class => 'btn btn-primary' }%>
        <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered ">
          <thead class="thead-default">
            <tr>
              <th>Name</th>
              <th>Position</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @players.each do |player| %>
              <tr>
                <td><%= link_to player.name, player %></td>
                <td><%= link_to player.position.name, player.position %></td>
                <td><%= link_to 'Edit', edit_player_path(player) %></td>
                <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    </div>
</div>

app/views/players/new.html.erb
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <h1>New Player</h1>
    </div>
</div>

<%= render 'form', player: @player %>
<div class="row">
    <div class="col-xs-12 col-md-4 offset-md-3">
        <%= link_to 'Back', players_path, { :class => 'btn btn-secondary'} %>
    </div>
</div>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
    <div class="col-xs-12 col-md-8">
        <h1><%= @player.name %></h1>

    </div>
    <div class="col-xs-12 col-md-8">
        <strong>Position:</strong>
        <%= @player.position.name %>
    </div>
    <div class="col-xs-12">
    <%= link_to 'Edit', edit_player_path(@player), { :class => 'btn btn-success'} %>
    <%= link_to 'Back', players_path, {:class => 'btn btn-secondary' } %>
    </div>
</div>